---
apiVersion: v1
kind: Namespace
metadata:
  name: prext
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prext-cluster-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - create
  - watch
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prext-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prext-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: prext
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prext-role
  namespace: prext
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prext-rolebinding
  namespace: prext
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prext-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: prext
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prext-server
  name: prext-server
  namespace: prext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prext-server
  template:
    metadata:
      labels:
        app: prext-server
    spec:
      containers:
      - image: ghcr.io/vishal-chdhry/prext:test
        name: prext-server
        imagePullPolicy: IfNotPresent
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace  
          - name: SERVICE_NAME
            value: prext-svc
          - name: DEPLOYMENT_NAME
            value: prext-server
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prext-server
  name: prext-svc
  namespace: prext
spec:
  ports:
  - port: 7443
    protocol: TCP
    targetPort: 7443
  selector:
    app: prext-server
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.prext.demo
spec:
  group: prext.demo
  version: v1alpha1
  groupPriorityMinimum: 100
  versionPriority: 100
  service:
    namespace: prext
    name: prext-svc
    port: 7443
