---
apiVersion: v1
kind: Namespace
metadata:
  name: prext
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prext
  namespace: prext
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prext-cluster-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - create
  - watch
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prext-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prext-cluster-role
subjects:
- kind: ServiceAccount
  name: prext
  namespace: prext
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prext-token-review-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: prext
  namespace: prext
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prext-role
  namespace: prext
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prext-rolebinding
  namespace: prext
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prext-role
subjects:
- kind: ServiceAccount
  name: prext
  namespace: prext
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "servicecatalog.k8s.io:apiserver-authentication-reader"
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: prext
  namespace: prext
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prext-server
  name: prext-server
  namespace: prext
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prext-server
  template:
    metadata:
      labels:
        app: prext-server
    spec:
      containers:
      - image: ghcr.io/vishal-chdhry/prext@sha256:fb3506e632fc77cef7d5f831676a1b118d82a7936b1e30b19179a9378c84de74
        name: prext-server
        imagePullPolicy: Always
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  
        - name: SERVICE_NAME
          value: prext-server
        - name: DEPLOYMENT_NAME
          value: prext-server
        - name: CERT_MANAGER_SECRET
          value: prext-cert-secret
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CERTPATH
          value: /certs/tls.crt
        - name: KEYPATH
          value: /certs/tls.key
      serviceAccountName: prext
      # volumes:
      # - secret:
      #     defaultMode: 420
      #     secretName: prext-cert-secret
      #   name: certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prext-server
  name: prext-server
  namespace: prext
spec:
  ports:
  - port: 7443
    protocol: TCP
    targetPort: 7443
  selector:
    app: prext-server
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: prext
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prext-server-cert
  namespace: prext
spec:
  dnsNames:
  - prext-server.prext.svc
  - prext-server.prext.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: ca-issuer
  secretName: prext-cert-secret
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.prext.demo
  annotations:
    cert-manager.io/inject-ca-from: prext/prext-server-cert
spec:
  group: prext.demo
  version: v1alpha1
  groupPriorityMinimum: 10
  versionPriority: 10
  service:
    namespace: prext
    name: prext-server
    port: 7443
